### ISSUE TITLE
Join Session button doesn't check if meeting id exists or not

### ISSUE THREAD

**Issue by saggins** [autoscriber-app/autoscriber-app.github.io#1]
Problem: 
Join Button doesn't check if the join endpoint returns a 406.
![image](https://user-images.githubusercontent.com/27894821/114322888-77979100-9ad7-11eb-8028-8c4d049abf84.png)
![image](https://user-images.githubusercontent.com/27894821/114322880-68b0de80-9ad7-11eb-8ba5-3757dfefcc96.png)
![image](https://user-images.githubusercontent.com/27894821/114322882-6cdcfc00-9ad7-11eb-8bb7-5c5e26f590c6.png)

**Comment by KentoNishi** [comment]
Now checks with `is_valid_meeting`
